CREATE DATABASE IF NOT EXISTS bot CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'bot'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON bot.* TO 'bot'@'%';

FLUSH PRIVILEGES;
